# Generated by Django 4.1 on 2022-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="telephone",
            field=models.TextField(default="01.23.45.67.89"),
            preserve_default=False,
        ),
    ]
