# Generated by Django 4.1 on 2022-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_location_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.BooleanField()),
                ('numero', models.TextField()),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
