# Generated by Django 4.1 on 2022-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.TextField()),
                ("type", models.TextField()),
                ("genre", models.TextField()),
                ("studios", models.TextField()),
                ("support", models.TextField()),
                ("annee", models.IntegerField()),
                ("etat", models.TextField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
