# Generated by Django 4.1 on 2022-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.TextField()),
                ("type", models.TextField()),
                ("entreprise", models.TextField()),
                ("adresse", models.TextField()),
                ("etat", models.TextField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
