# Generated by Django 4.1 on 2022-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="url",
            field=models.TextField(default="about:blank"),
            preserve_default=False,
        ),
    ]
